// <auto-generated />
using AluguelDeCasas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AluguelDeCasas.Migrations
{
	[DbContext(typeof(BancoContext))]
	partial class BancoContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
			#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("AluguelDeCasas.Models.ReservaPendenteModel", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

					b.Property<string>("Nome")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Contato")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("TipoEvento")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Pagamento")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ServicosAdd")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("DiaEntrada")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("DiaSaida")
						.IsRequired()
						.HasColumnType("nvarchar(max)");


					b.HasKey("Id");

					b.ToTable("ALUGUEL");
				});
			#pragma warning restore 612, 618

		}
	}


	[DbContext(typeof(BancoContextAprovados))]
	partial class BancoContextAprovadosModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
		#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("AluguelDeCasas.Models.ReservaPendenteModel", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int");

				SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

				b.Property<string>("Nome")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.Property<string>("Contato")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.Property<string>("TipoEvento")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.Property<string>("Pagamento")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.Property<string>("ServicosAdd")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.Property<string>("DiaEntrada")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.Property<string>("DiaSaida")
					.IsRequired()
					.HasColumnType("nvarchar(max)");


				b.HasKey("Id");

				b.ToTable("ALUGUEL");
			});
#pragma warning restore 612, 618

		}
	}


	[DbContext(typeof(BancoContextLogin))]
	partial class BancoContextLoginModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("AluguelDeCasas.Models.ReservaPendenteModel", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int");

				SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

				b.Property<string>("Nome")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.Property<string>("Contato")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.Property<string>("TipoEvento")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.Property<string>("Pagamento")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.Property<string>("ServicosAdd")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.Property<string>("DiaEntrada")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.Property<string>("DiaSaida")
					.IsRequired()
					.HasColumnType("nvarchar(max)");


				b.HasKey("Id");

				b.ToTable("ALUGUEL");
			});
#pragma warning restore 612, 618

		}
	}


}
